spring:
  servlet:
    multipart:
      max-file-size: 10MB #单个文件最大
      max-request-size: 100MB #总请求最大
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置druid数据源
    druid:
      filters: stat,wall,slf4j #底层开启功能,监控页和防火墙
      filter: #对上面的filters进行详细的配置
        stat:
          slow-sql-millis: 1000 #设置超过1000ms的都是慢查询
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false #禁止删除操作
      aop-patterns: com.zyj.admin.* #监控SpringBean
      stat-view-servlet:
        enabled: true #开启监控页
        login-username: admin #监控页账号
        login-password: 123456 #监控页密码
        reset-enable: false
      web-stat-filter: #监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gis,*.jpg,*.png,*.css,*.ico,/druid/*'
  jdbc:
    template:
      query-timeout: 3000 #超时时间
  mvc:
    hiddenmethod:
      filter:
        enabled: true
# Mybatis配置
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml #指定mybatis全局配置文件
  mapper-locations: classpath:/mapper/*.xml #指定sql映射文件
  configuration: # 指定mybatis全局配置文件相关配置项
    map-underscore-to-camel-case: true #开启驼峰命名自动映射
# management 是所有actuator监控的配置
management:
  endpoints:
    enabled-by-default: false #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点,web方式默认只暴露health和info
  endpoint:
    health:
      show-details: always # 查看健康状况总是显示详细信息
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true