# 配置静态资源访问路径前缀
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true #开启表单REST风格
  #    static-path-pattern: /res/**
# 覆盖springboot默认静态资源路径
  web:
    resources:
#      static-locations: [classpath:/re/]
      add-mappings: true  #false时可以禁用所有静态资源
      cache:
        period: 111111